// <auto-generated />
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240801182919_addProductsToDb")]
    partial class addProductsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Billy the Hero",
                            Description = "A beginner's guide for aspiring heroes, the Enchiridion is packed with essential advice for new adventurers. Learn the basics of combat, survival, and questing, along with tips for navigating the world of heroes. This book is the perfect starting point for anyone looking to embark on a heroic journey.",
                            ISBN = "ENC1234567",
                            ListPrice = 900.0,
                            Price = 850.0,
                            Price100 = 750.0,
                            Price50 = 800.0,
                            Title = "Enchiridion"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Xergoloth the Mad",
                            Description = "Dive into the dark arts with the Morellonomicon, a grimoire filled with forbidden spells and malevolent enchantments. This book is not for the faint-hearted, as it reveals the sinister paths of necromancy and demonology. Perfect for those who dare to harness the power of the shadows.",
                            ISBN = "MOR7654321",
                            ListPrice = 500.0,
                            Price = 490.0,
                            Price100 = 400.0,
                            Price50 = 450.0,
                            Title = "Morellonomicon"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Wardun the One-armed",
                            Description = "Designed for novice warriors, this manual provides a thorough introduction to the art of sword fighting. It covers basic techniques, footwork, and defensive maneuvers to build a solid foundation. Master the fundamentals and prepare yourself for any battle with confidence.",
                            ISBN = "SWD1010101",
                            ListPrice = 50.0,
                            Price = 45.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "Swordsmanship for Beginners"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Arch Wizard Toadbottom",
                            Description = "An essential handbook for aspiring spellcasters, Basics of Cantrips introduces readers to the simplest and most practical spells. This guide covers a variety of everyday enchantments, perfect for beginners looking to hone their magical skills. Start your journey into the magical arts with ease.",
                            ISBN = "BOC4445444",
                            ListPrice = 100.0,
                            Price = 90.0,
                            Price100 = 70.0,
                            Price50 = 80.0,
                            Title = "Basics of Cantrips"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Bob",
                            Description = "Explore the mysterious and dangerous creatures that inhabit the Black Woods with this detailed bestiary. Each entry provides descriptions, habits, and weaknesses of the forest's denizens, from the elusive Shadow Stalker to the fearsome Night Terror. Equip yourself with the knowledge to survive and thrive in the dark wilderness.",
                            ISBN = "BBW1122448",
                            ListPrice = 30.0,
                            Price = 29.0,
                            Price100 = 25.0,
                            Price50 = 27.0,
                            Title = "Bestiary of the Black Woods"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Moralla Goodman",
                            Description = "Navigate the moral dilemmas of adventuring with this updated guide on ethical behavior in the field. This edition covers new scenarios and offers advice on maintaining honor and integrity. A crucial resource for any adventurer committed to doing the right thing, even in the face of peril.",
                            ISBN = "AEE3333333",
                            ListPrice = 15.0,
                            Price = 14.0,
                            Price100 = 12.0,
                            Price50 = 13.0,
                            Title = "Adventuring Ethics 3rd Edition"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
